"""empty message

Revision ID: 06c22601aef2
Revises: cba44b8eb74f
Create Date: 2024-01-22 21:55:31.148694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06c22601aef2'
down_revision = 'cba44b8eb74f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('scientific_name', sa.String(), nullable=True),
    sa.Column('is_poisonous', sa.Boolean(), nullable=True),
    sa.Column('primary_color', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('plants')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plants',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('scientific_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_poisonous', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('primary_color', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='plants_pkey')
    )
    op.drop_table('plant')
    # ### end Alembic commands ###
